name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake .
    - name: make
      run: cmake --build .
    - name: test
      run: ./mdv_tests/mdv_tests
  build-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: ls -l $ANDROID_HOME/ndk-bundle
